name: Colorpicker
version: 1.0.3
description: Add colorpicker field type to Statamic V2
url: https://github.com/lesaff/statamic-colorpicker
developer: Rudy Affandi
developer_url: https://github.com/lesaff
